
name: install and test

on: [push]
jobs:
  build-xyz:
    name: "Run test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup
        uses: actions/checkout@v2
      - name: Set up JDK 17.0.1
        uses: actions/setup-java@v3
        with:
          java-version: '17.0.1'
      - name: Start MySQL
        run: |
          sudo service mysql start
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: '1.1.11'
      - name: Build it and they will come
        run: |
          poetry install
      - name: Initialize database
        env:
          SQLALCHEMY_URL: 'mysql+mysqlconnector://..'
        run: |
          mysql -u root -proot -e "CREATE DATABASE xyz"
          poetry run alembic upgrade head
      - name: Run test
        env: 
          SQLALCHEMY_URL: 'mysql+mysqlconnector://..'
        run: |
          poetry run LeapYearTest -r w
      - name: Send Ok notification
        if: success()&& github.ref== 'refs/head/main'
        uses: appleboy/telegram-action@master
        with:
          to: ${{secrets.TELEGRAM_TO}}
          token: ${{ secrets.TELEGRAM_TOKEN}}
          args: "xyz-main-api: All test passed. Lets go!"
      - name: Send failure notification
        if: failure()&& github.ref== 'refs/head/main'
        uses: appleboy/telegram-action@master
        with:
          to: ${{secrets.TELEGRAM_TO}}
          token: ${{ secrets.TELEGRAM_TOKEN}}
          args: "xyz-main-api: Warning: test failed!"
    

