name: install and test

on: [push]
jobs:
  build-xyz:
    name: "Run test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup
        uses: actions/checkout@v2
      - name: Set up JDK 17.0.1
        uses: actions/setup-java@v3
        with:
          java-version: '17.0.1'
      - name: Start MySQL
        run: |
          sudo service mysql start
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: '1.1.11'
    

