name: Maven Build

on:
  push:
    branches: [ master ]
jobs:

  build-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Set up JDK 17.0.1
        uses: actions/setup-java@v3
        with:
          java-version: 17.0.1
    
      - name: Step 3 - Build Maven Project
        run: |
          mvn -B package --file pom.xml
          mkdir staging && cp target/*.jar staging
          
      - name: Step 4 - Set up a cache for Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Step 5 - Persist workflow data as artificats
        uses: actions/upload-artifact@v3
        with:
          name: github-actions-artifact
          path: staging
